modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/KodoDenka/knavesneeds/issues"
license = "MIT"

[[mods]]
modId = "knavesneeds"
version = "${version}"
displayName = "Knaves' Needs"
authors = "KodoDenka"
description = '''
Additional swords for Simply Swords.

Special thanks to the following people for their contributions/influence on this mod:
- Sweeney/Sweenuss, for creating Simply Swords and supporting this addon.
- Chronos_Sacaria, for their support and help with the mod.
- LostLandFound, for creating and editing the textures for this project.
- daedelus, for creating Better Combat and helping this mod support it.
- Shedaniel, for creating Architectury.
- The Twilight Forest Team, for creating Twilight Forest.
- cesar_zorak, for creating Fobidden & Arcanus.
- The Modding Legacy Team, for creating Blue Skies.
'''
#logoFile = ""

[[dependencies.knavesneeds]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.knavesneeds]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.knavesneeds]]
modId = "architectury"
mandatory = true
versionRange = "[4.10.88,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.knavesneeds]]
modId = "simplyswords"
mandatory = true
versionRange = "[1.40.0-1.18.2,)"
ordering = "AFTER"
side = "BOTH"
