modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/KodoDenka/knavesneeds/issues"
license = "MIT"

[[mods]]
modId = "knavesneeds"
version = "${version}"
displayName = "Knaves' Needs"
authors = "KodoDenka"
description = '''
Additional swords for Simply Swords.

Special thanks to the following people for their contributions/influence on this mod:
- Sweeney/Sweenuss, for creating Simply Swords and supporting this addon.
- Chronos_Sacaria, for their support and help with the mod.
- LostLandFound, for creating and editing the textures for this project.
- daedelus, for creating Better Combat and helping this mod support it.
- Shedaniel, for creating Architectury.
- The Twilight Forest Team, for creating Twilight Forest.
- cesar_zorak, for creating Fobidden & Arcanus.
- The Modding Legacy Team, for creating Blue Skies.
'''
#logoFile = ""

[[dependencies.knavesneeds]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.knavesneeds]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.knavesneeds]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.knavesneeds]]
modId = "simplyswords"
mandatory = true
versionRange = "[1.48.0-1.21,)"
ordering = "AFTER"
side = "BOTH"

#Needs update
[[dependencies.knavesneeds]]
modId = "twilightforest"
mandatory = false
versionRange = "[4.2.1493,)"
ordering = "AFTER"
side = "BOTH"

#Needs update
[[dependencies.knavesneeds]]
modId = "blue_skies"
mandatory = false
versionRange = "[1.3,)"
ordering = "AFTER"
side = "BOTH"

#Needs update
[[dependencies.knavesneeds]]
modId = "forbidden_arcanus"
mandatory = false
versionRange = "[1.20.2-2.1.0,)"
ordering = "AFTER"
side = "BOTH"

#Add deeper darker.