plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

repositories {
    maven {
        name = "FzzyMaven"
        url = "https://maven.fzzyhmstrs.me/"
    }
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    modImplementation "me.fzzyhmstrs:fzzy_config:${project.fzzyConfigVersion}"
    modImplementation "curse.maven:simply-swords-659887:5639522"
    modImplementation "curse.maven:architectury-api-419699:5137936"
    modImplementation "curse.maven:cloth-config-348521:5729104"

    compileOnly "curse.maven:better-combat-by-daedelus-639842:7287333"

    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation project(":common")
}

loom {
    if (project(":common").file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.accesswidener"))
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
            source sourceSets.main
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
            source sourceSets.main
        }
        datagen {
            inherit client
            setConfigName("Fabric Data")
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${project(":fabric").file("src/main/generated")}"
            vmArg "-Dfabric-api.datagen.modid=knavesneeds"
            source sourceSets.main

            runDir "build/datagen"
        }
    }
}
