package net.knavesneeds.compat;

import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import net.knavesneeds.customitems.KnavesSwordItem;
import net.knavesneeds.registry.KnavesTeirRegistry;
import net.minecraft.item.Item;
import net.minecraft.util.registry.Registry;

import static net.knavesneeds.KnavesCommon.MOD_ID;
import static net.knavesneeds.registry.KnavesItemsRegistry.*;

public class ForbiddenArcanusCompat {

    public static final DeferredRegister<Item> FORBIDDEN_ARCANUS_ITEMS = DeferredRegister.create(MOD_ID, Registry.ITEM_KEY);

    //Arcane Golden
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_LONGSWORD = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_longsword", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + LONGSWORD_DAMAGE_MOD, LONGSWORD_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_TWINBLADE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_twinblade", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + TWINBLADE_DAMAGE_MOD, TWINBLADE_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_RAPIER = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_rapier", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + RAPIER_DAMAGE_MOD, RAPIER_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_KATANA = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_katana", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + KATANA_DAMAGE_MOD, KATANA_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_SAI = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_sai", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + SAI_DAMAGE_MOD, SAI_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_SPEAR = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_spear", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + SPEAR_DAMAGE_MOD, SPEAR_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_GLAIVE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_glaive", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + GLAIVE_DAMAGE_MOD, GLAIVE_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_WARGLAIVE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_warglaive", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + WARGLAIVE_DAMAGE_MOD, WARGLAIVE_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_CUTLASS = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_cutlass", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + CUTLASS_DAMAGE_MOD, CUTLASS_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_CLAYMORE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_claymore", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + CLAYMORE_DAMAGE_MOD, CLAYMORE_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_GREATHAMMER = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_greathammer", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + GREATHAMMER_DAMAGE_MOD, GREATHAMMER_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_GREATAXE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_greataxe", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + GREATAXE_DAMAGE_MOD, GREATAXE_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_CHAKRAM = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_chakram", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + CHAKRAM_DAMAGE_MOD, CHAKRAM_ATTACKSPEED));
    public static final RegistrySupplier<Item> ARCANE_GOLDEN_SCYTHE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/arcane_golden/arcane_golden_scythe", () -> new KnavesSwordItem(KnavesTeirRegistry.ARCANE_GOLDEN, ARCANE_GOLDEN_MOD + SCYTHE_DAMAGE_MOD, SCYTHE_ATTACKSPEED));

    //Draco Arcanus
    public static final RegistrySupplier<Item> DRACO_ARCANUS_LONGSWORD = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_longsword", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + LONGSWORD_DAMAGE_MOD, LONGSWORD_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_TWINBLADE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_twinblade", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + TWINBLADE_DAMAGE_MOD, TWINBLADE_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_RAPIER = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_rapier", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + RAPIER_DAMAGE_MOD, RAPIER_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_KATANA = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_katana", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + KATANA_DAMAGE_MOD, KATANA_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_SAI = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_sai", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + SAI_DAMAGE_MOD, SAI_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_SPEAR = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_spear", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + SPEAR_DAMAGE_MOD, SPEAR_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_GLAIVE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_glaive", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + GLAIVE_DAMAGE_MOD, GLAIVE_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_WARGLAIVE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_warglaive", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + WARGLAIVE_DAMAGE_MOD, WARGLAIVE_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_CUTLASS = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_cutlass", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + CUTLASS_DAMAGE_MOD, CUTLASS_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_CLAYMORE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_claymore", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + CLAYMORE_DAMAGE_MOD, CLAYMORE_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_GREATHAMMER = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_greathammer", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + GREATHAMMER_DAMAGE_MOD, GREATHAMMER_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_GREATAXE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_greataxe", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + GREATAXE_DAMAGE_MOD, GREATAXE_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_CHAKRAM = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_chakram", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + CHAKRAM_DAMAGE_MOD, CHAKRAM_ATTACKSPEED));
    public static final RegistrySupplier<Item> DRACO_ARCANUS_SCYTHE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/draco_arcanus/draco_arcanus_scythe", () -> new KnavesSwordItem(KnavesTeirRegistry.DRACO_ARCANUS, DRACO_ARCANUS_MOD + SCYTHE_DAMAGE_MOD, SCYTHE_ATTACKSPEED));

    //Reinforced Arcane Golden
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_LONGSWORD = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_longsword", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + LONGSWORD_DAMAGE_MOD, LONGSWORD_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_TWINBLADE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_twinblade", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + TWINBLADE_DAMAGE_MOD, TWINBLADE_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_RAPIER = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_rapier", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + RAPIER_DAMAGE_MOD, RAPIER_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_KATANA = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_katana", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + KATANA_DAMAGE_MOD, KATANA_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_SAI = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_sai", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + SAI_DAMAGE_MOD, SAI_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_SPEAR = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_spear", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + SPEAR_DAMAGE_MOD, SPEAR_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_GLAIVE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_glaive", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + GLAIVE_DAMAGE_MOD, GLAIVE_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_WARGLAIVE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_warglaive", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + WARGLAIVE_DAMAGE_MOD, WARGLAIVE_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_CUTLASS = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_cutlass", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + CUTLASS_DAMAGE_MOD, CUTLASS_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_CLAYMORE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_claymore", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + CLAYMORE_DAMAGE_MOD, CLAYMORE_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_GREATHAMMER = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_greathammer", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + GREATHAMMER_DAMAGE_MOD, GREATHAMMER_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_GREATAXE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_greataxe", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + GREATAXE_DAMAGE_MOD, GREATAXE_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_CHAKRAM = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_chakram", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + CHAKRAM_DAMAGE_MOD, CHAKRAM_ATTACKSPEED));
    public static final RegistrySupplier<Item> REINFORCED_ARCANE_GOLDEN_SCYTHE = FORBIDDEN_ARCANUS_ITEMS.register("forbidden_arcanus/reinforced_arcane_golden/reinforced_arcane_golden_scythe", () -> new KnavesSwordItem(KnavesTeirRegistry.REINFORCED_ARCANE_GOLDEN, REINFORCED_ARCANE_GOLDEN_MOD + SCYTHE_DAMAGE_MOD, SCYTHE_ATTACKSPEED));

}
